/// FFI bridge to eacompute SIMD kernels (.ea compiled to .so).
/// Feature-gated behind `ea` — falls back to scalar Rust when disabled.
///
/// Safety: all FFI calls pass raw pointers into caller-owned slices.
/// Lengths are checked before every call. No allocations in FFI land.

// ---- FFI declarations (generated by `ea bind --rust`, inlined here) ----

extern "C" {
    fn motion_fused(
        prev: *const u8,
        curr: *const u8,
        grid_counts: *mut u32,
        width: i32,
        height: i32,
        threshold: i32,
        cell_size: i32,
        cols: i32,
    ) -> i32;

    fn normalize_u8_f32(
        input: *const u8,
        out: *mut f32,
        n: i32,
        scale: f32,
        bias: f32,
    );

    fn relayout_conv_weights(
        src: *const i8,
        dst: *mut i8,
        c_out: i32,
        c_in: i32,
    );

    fn conv3x3_relu_pool(
        input: *const f32,
        in_w: i32,
        in_h: i32,
        c_in: i32,
        weights: *const i8,
        bias: *const i8,
        c_out: i32,
        output: *mut f32,
    );

    fn gap_fc_softmax(
        input: *const f32,
        w: i32,
        h: i32,
        channels: i32,
        fc_weights: *const i8,
        fc_bias: *const i8,
        scores_out: *mut f32,
        num_classes: i32,
    );
}

// ---- Safe wrappers ----

/// Fused motion detection: abs-diff + threshold + grid counting.
/// Returns total number of changed pixels.
pub fn ea_motion_fused(
    prev: &[u8],
    curr: &[u8],
    grid_counts: &mut [u32],
    width: u32,
    height: u32,
    threshold: u8,
    cell_size: u32,
    cols: u32,
) -> u32 {
    debug_assert_eq!(prev.len(), (width * height) as usize);
    debug_assert_eq!(curr.len(), (width * height) as usize);
    debug_assert!(grid_counts.len() >= (cols * ((height + cell_size - 1) / cell_size)) as usize);

    let result = unsafe {
        motion_fused(
            prev.as_ptr(),
            curr.as_ptr(),
            grid_counts.as_mut_ptr(),
            width as i32,
            height as i32,
            threshold as i32,
            cell_size as i32,
            cols as i32,
        )
    };
    result as u32
}

/// Normalize u8 frame to f32: out[i] = input[i] * scale + bias.
/// For CNN input, use scale = 1.0/127.5, bias = -1.0.
pub fn ea_normalize_u8_f32(input: &[u8], out: &mut [f32], scale: f32, bias: f32) {
    debug_assert!(out.len() >= input.len());

    unsafe {
        normalize_u8_f32(
            input.as_ptr(),
            out.as_mut_ptr(),
            input.len() as i32,
            scale,
            bias,
        );
    }
}

/// Relayout conv weights from [c_out][c_in][3][3] to [c_out][3][3][c_in].
/// Called once at model load, not on the hot path.
pub fn ea_relayout_conv_weights(src: &[i8], dst: &mut [i8], c_out: usize, c_in: usize) {
    debug_assert_eq!(src.len(), c_out * c_in * 9);
    debug_assert_eq!(dst.len(), c_out * c_in * 9);

    unsafe {
        relayout_conv_weights(
            src.as_ptr(),
            dst.as_mut_ptr(),
            c_out as i32,
            c_in as i32,
        );
    }
}

/// Fused conv3x3 + bias + ReLU + 2x2 max-pool.
/// Weights must be in [c_out][3][3][c_in] layout (use ea_relayout_conv_weights first).
pub fn ea_conv3x3_relu_pool(
    input: &[f32],
    in_w: usize,
    in_h: usize,
    c_in: usize,
    weights: &[i8],
    bias: &[i8],
    c_out: usize,
    output: &mut [f32],
) {
    let out_w = in_w / 2;
    let out_h = in_h / 2;
    debug_assert!(input.len() >= in_w * in_h * c_in);
    debug_assert_eq!(weights.len(), c_out * c_in * 9);
    debug_assert_eq!(bias.len(), c_out);
    debug_assert!(output.len() >= out_w * out_h * c_out);

    unsafe {
        conv3x3_relu_pool(
            input.as_ptr(),
            in_w as i32,
            in_h as i32,
            c_in as i32,
            weights.as_ptr(),
            bias.as_ptr(),
            c_out as i32,
            output.as_mut_ptr(),
        );
    }
}

/// Fused global average pooling + fully-connected + softmax.
pub fn ea_gap_fc_softmax(
    input: &[f32],
    w: usize,
    h: usize,
    channels: usize,
    fc_weights: &[i8],
    fc_bias: &[i8],
    scores_out: &mut [f32],
    num_classes: usize,
) {
    debug_assert!(input.len() >= w * h * channels);
    debug_assert_eq!(fc_weights.len(), channels * num_classes);
    debug_assert_eq!(fc_bias.len(), num_classes);
    debug_assert!(scores_out.len() >= num_classes);

    unsafe {
        gap_fc_softmax(
            input.as_ptr(),
            w as i32,
            h as i32,
            channels as i32,
            fc_weights.as_ptr(),
            fc_bias.as_ptr(),
            scores_out.as_mut_ptr(),
            num_classes as i32,
        );
    }
}
