use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    if env::var("CARGO_FEATURE_EA").is_err() {
        return;
    }

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let repo_root = PathBuf::from(&manifest_dir).join("../..");

    let arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap();
    let arch_dir = match arch.as_str() {
        "x86_64" => "x86_64",
        "aarch64" => "aarch64",
        _ => panic!("unsupported target arch for ea kernels: {arch}"),
    };

    let kernel_dir = repo_root.join("kernels/prebuilt").join(arch_dir);
    if !kernel_dir.exists() {
        panic!(
            "Pre-built kernels not found at {}\n\
             Run ./build.sh to compile from .ea sources",
            kernel_dir.display()
        );
    }

    let kernels = ["motion", "inference", "normalize"];
    let mut code = String::from("// Auto-generated by build.rs — do not edit\n");

    for name in &kernels {
        let so_path = kernel_dir.join(format!("lib{name}.so"));
        let abs = so_path.canonicalize().unwrap_or_else(|_| {
            panic!("Kernel not found: {so_path:?}");
        });
        let upper = name.to_uppercase();
        code.push_str(&format!(
            "pub const {upper}: &[u8] = include_bytes!(\"{}\");\n",
            abs.display()
        ));
    }

    let version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());
    code.push_str(&format!("pub const VERSION: &str = \"{version}\";\n"));

    fs::write(PathBuf::from(&out_dir).join("embedded_kernels.rs"), &code).unwrap();

    for name in &kernels {
        let so_path = kernel_dir.join(format!("lib{name}.so"));
        println!("cargo:rerun-if-changed={}", so_path.display());
    }
}
